name: Build Plugin for Linux ARM64

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build Plugin
        run: dotnet build MultiLineFishing.csproj -c Release -p:Platform=AnyCPU

      - name: Upload Plugin DLL
        uses: actions/upload-artifact@v4
        with:
          name: MultiLineFishing
          path: bin/Release/net6.0/MultiLineFishing.dll